name: Push-to-EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ROHIT_KEY }}
          SOURCE: "index.html"
          REMOTE_HOST: "13.115.55.255"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html"
          
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-northeast-1

      - name: Move logs to S3
        run: |
         echo " ${{ github. run_id }} "
         echo " ${{ github.workspace }} "
         aws s3 cp ${{ github.workspace }} s3://githublog/logs${{ github. run_id }} --recursive  
