name: Push-on-ec2-machine

on: push

jobs:
  build:
    name: Build HTML image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-html-image .

  test:
    name: Test
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."

  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ROHIT_KEY }}
          SOURCE: "my-html-image:latest"
          REMOTE_HOST: "13.112.71.179"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/html"
